<?php

namespace Database\Seeders;

use App\Models\Album;
use App\Models\Track;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrackSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tracks')->truncate();

        $albums = [
            'Appalachian Stomp: Bluegrass Classics' => [
                'Orange Blossom Special',
                'Rocky Top',
                'Foggy Mountain Breakdown',
                'Dueling Banjos',
                'Blue Moon of Kentucky',
                'Roll in My Sweet Baby\'s Arms',
                'Will the Circle Be Unbroken',
                'I Am a Man of Constant Sorrow',
                'Nine Pound Hammer',
                'Salty Dog Blues',
            ],
            'Clawhammer Banjo (Volume 1) - Wade Ward' => [
                'Cripple Creek',
                'Sourwood Mountain',
                'Old Joe Clark',
                'June Apple',
                'Shady Grove',
                'Boll Weevil',
                'Fly Around My Pretty Little Miss',
                'Ducks on the Millpond',
                'Arkansas Traveler',
                'Last Chance',
            ],
            'Old Time Music at Clarence Ashley\'s' => [
                'The Coo Coo Bird',
                'Dark Holler',
                'Old Reuben',
                'Amazing Grace',
                'The House Carpenter',
                'Walking Boss',
                'East Virginia Blues',
                'Handsome Molly',
                'Little Sadie',
                'Shady Grove',
            ],
            'Hollow Poplar - Bruce Molsky' => [
                'Hollow Poplar',
                'Cold Frosty Morning',
                'Ducks on the Millpond',
                'John Brown\'s Dream',
                'Sandy River Belle',
                'Sail Away Ladies',
                'Shooting Creek',
                'Kitchen Girl',
                'Last Chance',
                'Wild Horse',
            ],
            'Say Old Man - Dirk Powell' => [
                'Say Old Man',
                'Waterbound',
                'Poor Ellen Smith',
                'Roustabout',
                'Angeline the Baker',
                'Lost Indian',
                'Bonaparte\'s Retreat',
                'Old Molly Hare',
                'Cluck Old Hen',
                'Sugar Hill',
            ],
            'Sail Away Ladies - Uncle Bunt Stephens' => [
                'Sail Away Ladies',
                'Old Hen Cackled',
                'Wolves A-Howling',
                'Give the Fiddler a Dram',
                'Leather Britches',
                'Cackling Hen',
                'Jenny on the Railroad',
                'Sugar in the Gourd',
            ],
            'Round Peak Style - Tommy Jarrell' => [
                'Sally Ann',
                'John Henry',
                'Breaking Up Christmas',
                'Sally Goodin',
                'Backstep Cindy',
                'Joke on the Puppy',
                'Drunken Hiccups',
                'Camp Chase',
                'Black Mountain Rag',
                'Sail Away Ladies',
            ],
            'June Apple - Red Clay Ramblers' => [
                'June Apple',
                'Old Molly Hare',
                'Georgia Railroad',
                'Soldier\'s Joy',
                'Cotton-Eyed Joe',
                'Sally Goodin',
                'Flop Eared Mule',
                'Fire on the Mountain',
                'Ragtime Annie',
                'Liberty',
            ],
            'The Skillet Lickers - Old Time Fiddle Tunes' => [
                'Bully of the Town',
                'Pass Around the Bottle',
                'Devilish Mary',
                'Watermelon on the Vine',
                'Ida Red',
                'Turkey in the Straw',
                'Chicken Reel',
                'Down Yonder',
                'Alabama Jubilee',
                'Run Nigger Run',
            ],
            'Foggy Mountain Special - Highwoods Stringband' => [
                'Foggy Mountain Special',
                'Fire on the Mountain',
                'Cluck Old Hen',
                'Wild Bill Jones',
                'Walk Along John',
                'Indian Ate the Woodchuck',
                'Mississippi Sawyer',
                'Going Across the Sea',
                'Rock the Cradle Joe',
                'Sugar in the Gourd',
            ],
            'Bluegrass Breakdown - Bill Monroe' => [
                'Bluegrass Breakdown',
                'Heavy Traffic Ahead',
                'Toy Heart',
                'Blue Moon of Kentucky',
                'Molly and Tenbrooks',
                'Footprints in the Snow',
                'Wicked Path of Sin',
                'It\'s Mighty Dark to Travel',
                'When You Are Lonely',
                'Little Community Church',
            ],
            'Foggy Mountain Banjo - Earl Scruggs' => [
                'Cripple Creek',
                'Cumberland Gap',
                'Old Joe Clark',
                'John Henry',
                'Randy Lynn Rag',
                'Fireball Mail',
                'Ground Speed',
                'Sally Goodin',
                'Reuben',
                'Flint Hill Special',
                'Sally Ann',
                'Home Sweet Home',
            ],
            'Will the Circle Be Unbroken - Nitty Gritty Dirt Band' => [
                'Grand Ole Opry Song',
                'Keep on the Sunny Side',
                'Nashville Blues',
                'You Are My Flower',
                'Mr. Bojangles',
                'Honky Tonkin\'',
                'You Don\'t Know My Mind',
                'My Walkin\' Shoes',
                'Lonesome Fiddle Blues',
                'Lost Highway',
                'Cannonball Rag',
                'Will the Circle Be Unbroken',
            ],
            'Rounder Records Bluegrass Collection' => [
                'Big Mon',
                'Blue Ridge Cabin Home',
                'White House Blues',
                'Little Maggie',
                'John Hardy',
                'Shady Grove',
                'Pretty Polly',
                'Banks of the Ohio',
                'Man of Constant Sorrow',
                'Wayfaring Stranger',
            ],
            'Old & In the Way - Jerry Garcia' => [
                'Pig in a Pen',
                'Midnight Moonlight',
                'Old and In the Way',
                'Knockin\' on Your Door',
                'The Hobo Song',
                'Panama Red',
                'Wild Horses',
                'Kissimmee Kid',
                'White Dove',
                'Land of the Navajo',
            ],
            'Appalachian Swing - Doc Watson' => [
                'Black Mountain Rag',
                'Beaumont Rag',
                'Appalachian Swing',
                'Doc\'s Guitar',
                'Sweet Georgia Brown',
                'Windy and Warm',
                'Dill Pickle Rag',
                'Bye Bye Blues',
                'Farewell Blues',
            ],
            'The Essential Flatt & Scruggs' => [
                'Foggy Mountain Breakdown',
                'Earl\'s Breakdown',
                'Flint Hill Special',
                'Salty Dog Blues',
                'Ballad of Jed Clampett',
                'Roll in My Sweet Baby\'s Arms',
                'Cabin on the Hill',
                'Don\'t Let Your Deal Go Down',
                'Pike County Breakdown',
                'Nashville Skyline Rag',
            ],
            'Hot Rize - Traditional Ties' => [
                'Nellie Kane',
                'Colleen Malone',
                'Just Like You',
                'Radio Boogie',
                'Untold Stories',
                'Blue Night',
                'Won\'t You Come and Sing for Me',
                'Keep On the Sunny Side',
                'Traditional Ties',
                'Shaker Town',
            ],
            'Tony Rice - Manzanita' => [
                'Manzanita',
                'Old Train',
                'Blue Railroad Train',
                'Ride the Wild Turkey',
                'Streets of London',
                'Shenandoah',
                'Nine Pound Hammer',
                'Jerusalem Ridge',
                'Red Haired Boy',
                'Last Thing on My Mind',
            ],
            'Strength in Numbers - Telluride Sessions' => [
                'Limerock',
                'Duchess of Mull',
                'Mars Ain\'t a Good Place to Raise Kids',
                'Climb',
                'Life\'s Railway to Heaven',
                'Army of Angels',
                'Ride',
                'For Bela',
                'The Valley',
                'Telluride',
            ],
            'The Bothy Band - 1975' => [
                'Farewell to Erin',
                'The Salamanca / The Banshee / The Tarbolton',
                'Do You Love an Apple',
                'The Morning Star / The Leitrim Fancy',
                'Fionnghuala',
                'Music in the Glen / The Flowers of Red Hill',
                'The Death of Queen Jane',
                'Calum Sgaire / John Sharp / Timmy the Lepper',
            ],
            'Planxty - The Black Album' => [
                'Raggle Taggle Gypsy / Tabhair Dom Do Lamh',
                'Cold Blow and the Rainy Night',
                'Sí Bheag Sí Mhór',
                'Junior Crehan\'s Favourite / Molly on the Shore',
                'The Blacksmith',
                'Merrily Kissed the Quaker',
                'The West Coast of Clare',
                'As I Roved Out',
                'Planxty Irwin',
            ],
            'The Chieftains 4' => [
                'Drowsy Maggie',
                'Morgan Magan',
                'The Bucks of Oranmore',
                'The Tip of the Whistle',
                'The Battle of Aughrim',
                'The Morning Dew',
                'Carolan\'s Concerto',
                'The Frieze Britches',
                'Mná na hÉireann',
            ],
            'De Dannan - Selected Jigs Reels & Songs' => [
                'The Rambling Pitchfork',
                'Kitty\'s Wedding',
                'The Blackberry Blossom',
                'The Jig of Slurs',
                'Hey Jude',
                'The Bucks of Oranmore',
                'The Queen of May',
                'Carolans Draught',
                'My Irish Molly',
                'The Gold Ring',
            ],
            'Martin Hayes - Under the Moon' => [
                'The Lament for Limerick / The Maids of Mount Cisco',
                'The Green Fields of Rossbeigh',
                'Under the Moon',
                'Gavin\'s March / Paddy Fahey\'s Reel',
                'The Lonesome Jig / Out on the Road',
                'Bon Accord / Lucy Campbell\'s',
                'The Ash Plant / The Templehouse',
                'Cradle Song',
            ],
        ];

        foreach ($albums as $albumName => $tracks) {
            $album = Album::where('name', $albumName)->first();
            if (! $album) {
                continue;
            }

            foreach ($tracks as $index => $trackName) {
                Track::create([
                    'album_id' => $album->id,
                    'name' => $trackName,
                    'track_number' => $index + 1,
                ]);
            }
        }
    }
}
